spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_FQDN:http://localhost:9001}
      name: subrecommend-service
      profile: default
      label: main
  config:
    import: "optional:configserver:"